### ISSUE TITLE
Mario Kart 7 - Crashes on Lap 2 of the 4th Race (Cup 2)

### ISSUE THREAD

**Issue by initPRAGMA** [citra-emu/citra-bleeding-edge#24]
**Version:** HEAD-b79ad3b (0.1.116 - Has been happening since build 90)

`Unhandled exception at 0x000000002CB0F09A in citra-qt.exe: 0xC0000005: Access violation reading location 0x00000000091F1F10.`

Whenever you go to the 4th race on Cup 2 (Tested on 150cc), And you get to [this](http://i.imgur.com/tysYHAH.png) specific area, it will crash for whatever reason.

I tested on a Nightly and this didn't happen as it had some kind of implementation where whenever a SFX had not been implemented it would use either BLACK or just a random image (In my case it was mostly Position Number images) and because of that maybe in that area on lap 2, some kind of big SFX happens and since it was covered by either a random image or black, it could actually render leading it to not crash? Who knows.

**Disassembly:**
![Disassembly](http://i.imgur.com/tyzcJzf.png)

**Call Stack:**
![Call Stack](http://i.imgur.com/ArrYj7g.png)

**Autos:**
![Autos](http://i.imgur.com/HPx194j.png)

_Locals is empty and "Source is not available."_

**Comment by khang06** [comment]
This happens in a ton of other places, too. (Rainbow Road, Waluigi Pinball, and others)

**Comment by JayFoxRox** [comment]
Use the forums instead if you need help: https://community.citra-emu.org/
Bug reports which affect nightly should be on the citra-emu/citra repo instead (where actual development happens).

**Comment by Dragios** [comment]
@JayFoxRox It did not happen in the nightly builds, which is why I called him to open the issue here.

**Comment by JayFoxRox** [comment]
See #29. We are still not sure how the issues will be used in these repos.

This and the citra-nightly repo are merely archives and temporary storage for the releases.
However, issues with this repo will mostly be about packaging and bot issues which also have their respective repos (part of citra-emu/citra and citra-emu/bleeding-edge-bot).

The only thing which was useful for issues was the bleeding-edge-base branch, but it has since been moved to the jroweboy/citra-bleeding-edge repo.

---

Also there is no support for bleeding edge (see downloads page).
If there is an issue in one of the upcoming changes those should be reported via the forums (for now) or directly bisected and reported in the particular PR discussion.

PS: SFX is usually "Sound Effects".
