### ISSUE TITLE
Please add a changelog

### ISSUE THREAD

**Issue by jezaman** [citra-emu/citra-bleeding-edge#39]
Why does this project not have a changelog? 
How would i know if it's worth using bleeding edge or not?, if you don't mention the changes?
Also, would be nice to have some sort of visualisation to show which (and when) bleeding edge features get integrated into the main project..

**Comment by jroweboy** [comment]
A changelog would need to be written by a real person and can't easily be automated. As Bleeding edge releases can happen very frequently, some days you might need to write 2 or more patch notes. To make it more annoying, you would need to get them written within a few hours of release if you actually want people to use it. Bleeding edge already has a merge list which is about the best we can do. Just check the readme file in the release for that. 

> Also, would be nice to have some sort of visualisation to show which (and when) bleeding edge features get integrated into the main project..

Sounds fine, but please describe what you picture this visualization to look like.

**Comment by RavenHome1** [comment]
you can always add citra to your github watch and skim through PR to see what they change/ improve

you can also visit /r/Citra/ and /r/emulation/ on reddit to find some up to date news about citra or emulators in general

**Comment by JayFoxRox** [comment]
We already have the mergelogs (as part of the README) and the development process is very transparent, so a changelog for BE is not intended. As you (unrelated I might add) asked for a project-wide (infrastructure included) changelog: not going to happen due to how difficult it would be for us to maintain such a log.
If you meant "emu" project then we'd still not do it for BE as stated above, for nightly builds it's not really realistic either (too much work = would slow the project down) and for stable releases this will lightly happen (if they are ever a thing).

Note that all releases of Citra are development builds, not actual stable / version numbered releases.
You can't expect a similar documentation  for unstable releases.
We'll probably slowly catch up with documentation in general, but depending on how we do releases changelogs may never be a thing (aside from blog posts once in a while for larger changes).

You are free to start your own Citra changelog project and offload this task from the main devs.

I'll close this now.
